theme: jekyll-theme-midnight
title: Tadukooverse
description: Official website of Tadukooverse
collections:
  about:
    output: true
  changelogs:
    output: true
  community:
    output: true
  contributors:
    output: true
  guides:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "about"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "changelogs"
    values:
      layout: "changelog"
  - scope:
      path: ""
      type: "community"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "contributors"
    values:
      layout: "contributor"
      toc_off: true
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      replaced: false
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jemoji
  