theme: jekyll-theme-midnight
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jemoji
  